### ISSUE TITLE
binds 组合普通函数和Promise，最后的返回结果一定是一个Promise。

### ISSUE THREAD

**Issue by inshua** [kalxd/photon#1]
这种习惯上是叫 chain 吧，如：

```js
fun1.chain(fun2).chain(fun3).bind(obj).call()
```

将挨个执行 fun1, fun2, fun3
其中 bind 意思为绑定 this 对象。

**Comment by inshua** [comment]
还有一个名字：seq，seq 是与 parallel （并行）对应的，表示串行

**Comment by kalxd** [comment]
* `binds`更名为`compose`
* `mbinds`更名为`mcompose`

以后可能真的会出另一个`binds`函数。

同时更新了README。
